apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: cnoe://coredns/manifests
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
