apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubeflow.github.io/spark-operator
      targetRevision: 1.1.27
      helm:
        releaseName: spark-operator
      chart: spark-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
