apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: local-secret
      key: creds
  endpoint:
    hostnameImmutable: true
    url:
      type: Static
      static: http://localhost.localstack.cloud:4566
