apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: crossplane-system
stringData:
  creds: |
    [default]
    aws_access_key_id = replaceme
    aws_secret_access_key = replaceme
    aws_session_token = replacemeifneeded
