project_name: idpbuilder

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.idpbuilderVersion={{ .Version }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.gitCommit={{ .FullCommit }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.buildDate={{ .CommitDate }}
      - -w
      - -s
    binary: idpbuilder
    ignore:
      - goos: linux
        goarch: '386'
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{- if contains .Tag "nightly" }}{{ .Tag }}-{{ end }}{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

