version: 2
project_name: idpbuilder

before:
  hooks:
    - go mod tidy
release:
  # Mark nightly build as prerelease based on tag
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.idpbuilderVersion={{ .Version }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.gitCommit={{ .FullCommit }}
      - -X github.com/cnoe-io/idpbuilder/pkg/cmd/version.buildDate={{ .CommitDate }}
      - -w
      - -s
    binary: idpbuilder
    ignore:
      - goos: linux
        goarch: '386'
brews:
# For non version installations
  - name: "idpbuilder" 
    homepage: "https://cnoe.io"
    skip_upload: "{{ contains .Tag \"nightly\" }}" # Don't upload this formula if the build is nightly
    repository:
      owner: cnoe-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: "CNOEAutomation"
      email: "noreply@cnoe.io"
    directory: Formula
    install: |
      bin.install "idpbuilder"
    test: |
      system "#{bin}/idpbuilder version"
# For versioned and nightly installations
  - name: "{{ if contains .Tag \"nightly\" }}idpbuilder-nightly{{ else }}idpbuilder@{{ .Major }}.{{ .Minor }}.{{ .Patch }}{{ end }}"
    homepage: "https://cnoe.io"
    repository:
      owner: cnoe-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: "CNOEAutomation"
      email: "noreply@cnoe.io"
    directory: Formula
    install: |
      bin.install "idpbuilder"
    test: |
      system "#{bin}/idpbuilder version"
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  use: github
  format: "{{.SHA}}: {{.Message}} [{{.AuthorName}}](@{{.AuthorUsername}})" 
  groups:
    - title: "✨ Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug fixes"
      regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Others"
      order: 999
