# For more information, visit: https://pre-commit.com
# To run locally:
# 1. Install pre-commit: pip install pre-commit
# 2. Run pre-commit checks on all files: pre-commit run --all-files

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ["--skip=*.excalidraw,*.git,*.png,*.jpg,*.svg,go.sum,go.mod,./pkg/controllers/localbuild/resources"]
