apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  ports:
  - name: edge
    port: 4566
    targetPort: 4566
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
