apiVersion: v1
stringData:
  test: data
kind: Secret
metadata:
  labels:
    Test: Data
  name: secret-one
---
apiVersion: v1
stringData:
  test: data
kind: Secret
metadata:
  labels:
    Test: Data
  name: secret-two
---
apiVersion: v1
kind: Service
metadata:
  labels:
    test: test
  name: ingress-nginx-controller-admission
  namespace: ingress-nginx
spec:
  ports:
    - appProtocol: https
      name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: ClusterIP
