apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  allow-snippet-annotations: "true"
  proxy-buffer-size: "32k"
  proxy-busy-buffers-size: "32k"
  use-forwarded-headers: "true"
