apiVersion: idpbuilder.cnoe.io/v1alpha2
kind: ArgoCDProvider
metadata:
  name: my-argocd
  namespace: argocd
spec:
  # Namespace where ArgoCD will be deployed
  namespace: argocd
  
  # Version of ArgoCD to install
  version: "v2.12.0"
  
  # Admin credentials configuration
  adminCredentials:
    # Auto-generate admin credentials (creates a secret)
    autoGenerate: true
    # Optional: reference to existing secret
    # secretRef:
    #   name: argocd-admin-secret
    #   namespace: argocd
    #   key: password
  
  # Optional: ArgoCD projects to create
  # projects:
  #   - name: default
  #     description: Default project for applications
