apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
        - args:
          - /usr/local/bin/argocd-server
          - "{{if .UsePathRouting}}"
          - --insecure
          - --basehref
          - /argocd
          - "{{end}}"
          name: argocd-server
          imagePullPolicy: IfNotPresent
