apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: argo
spec:
  secretStoreRef:
    name: keycloak
    kind: ClusterSecretStore
  target:
    name: keycloak-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_ID
    - secretKey: secret-key
      remoteRef:
        key: keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_SECRET
