name: Feature Proposal
description: 'Submit a proposal for a new feature'
title: 'Feature: <title>'
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ### Creating feature request:

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Remain clear and concise.
        - Use of examples is a big plus.

  - type: checkboxes
    id: duplicate
    attributes:
      label: 'Have you searched for this feature request?'
      options:
        - label: "I searched but did not find similar requests"
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 'Problem Statement'
      description: 'Please provide a clear and concise problem statement'
      placeholder: 'idpbuilder does this right now, but this does not support my use case because...'

  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: 'Possible Solution'
      description: 'Please explain what you think is a good solution for this problem'
      placeholder: 'I think idpbuilder should do this and that...'

  - type: textarea
    id: alternatives
    validations:
      required: false
    attributes:
      label: 'Alternatives Considered'
      description: 'Please provide any alternative solutions you have considered'
      placeholder: 'OPTIONAL. Providing this information helps us follow your thought process'
