# Kind kubernetes release images https://github.com/kubernetes-sigs/kind/releases
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:{{ .KubernetesVersion }}"
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=4Gi
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 443
    hostPort: {{ .Port }}
    protocol: TCP
  {{ range .ExtraPortsMapping }}- containerPort: {{ .ContainerPort }}
    hostPort: {{ .HostPort }}
    protocol: TCP{{ end }}