---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-argo-workflows-ingress
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: argo-workflows
                # anything not staging or prod use this version
                addonChartVersion: 0.40.14
                addonChartRepository: https://argoproj.github.io/argo-helm
              selector:
                matchExpressions:
                  - key: akuity.io/argo-cd-cluster-name
                    operator: NotIn
                    values: [in-cluster]
                  - key: enable_aws_argo_workflows_ingress
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: staging
              values:
                addonChartVersion: 0.40.14
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 0.40.14
  template:
    metadata:
      name: addon-{{.name}}-aws-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/default/addons/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}environments/{{.metadata.labels.environment}}/addons/{{.values.addonChart}}/values.yaml
              - $values/{{.metadata.annotations.addons_repo_basepath}}clusters/{.{name}}/addons/{{.values.addonChart}}/values.yaml
            values: |
              server:
                serviceType: ClusterIP
                servicePort: 2746
                servicePortName: http
                ingress:
                  enabled: true
                  annotations:
                    alb.ingress.kubernetes.io/scheme: "internet-facing"
                    alb.ingress.kubernetes.io/target-type: "ip"
                    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
                    alb.ingress.kubernetes.io/listen-ports: "[{\"HTTPS\":443}]"
                    alb.ingress.kubernetes.io/tags: "Environment=hub,GitOps=true"
                  ingressClassName: "alb"
                  hosts: {{.metadata.annotations.argo_workflows_hosts}}
                  paths:
                    - /
                  pathType: Prefix
                  tls:
                  - hosts: {{.metadata.annotations.argo_workflows_hosts}}
      destination:
        namespace: '{{default "argo-workflows" .metadata.annotations.argo_workflows_namespace}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.