apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-localstack
  namespace: argocd
  labels:
    example: localstack-integration
spec:
  project: default
  source:
    repoURL: cnoe://crossplane-provider-localstack
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
