kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:v1.27.3"
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraMounts:
    - hostPath: /home/ubuntu/backup # replace with your own path
      containerPath: /backup
  extraPortMappings:
  - containerPort: 443
    hostPort: {{ .Port }}
    protocol: TCP
