apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.min.io'
      targetRevision: 5.0.15
      helm:
        releaseName: minio
        valueFiles:
          - $values/helm/values.yaml
      chart: minio
    - repoURL: cnoe://minio
      targetRevision: HEAD
      ref: values
    - repoURL: cnoe://minio
      targetRevision: HEAD
      path: "manifests"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
