{%- if values.awsResources %}
resources:
{%- if 'Bucket' in values.awsResources %}
  - ../base/
{%- endif %}
{%- if 'Table' in values.awsResources %}
  - ../base/table.yaml
{%- endif %}
{%- endif %}
namespace: default

patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
        labels:
          backstage.io/kubernetes-id: ${{values.name}}
      spec:
        template:
          metadata:
            labels:
              backstage.io/kubernetes-id: ${{values.name}}
  - target:
      kind: Service
    patch: |
      apiVersion: apps/v1
      kind: Service
      metadata:
        name: not-used
        labels:
          backstage.io/kubernetes-id: ${{values.name}}
