# velero backup create nginx-backup --selector app=nginx
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: nginx-backup
  namespace: velero
spec:
  includedNamespaces:
    - '*'
  labelSelector:
    matchLabels:
      app: nginx
