apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name | dump}}
  namespace: default
  labels:
    entity-id: ${{values.name}}
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        entity-id: ${{values.name}}
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
